package spaceinvaders.frontend;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import spaceinvaders.backend.files.GameState;
import spaceinvaders.backend.files.GameStateManager;

/**
 *
 * @author saien
 */
public class Principal extends javax.swing.JFrame {

    private String PATH_BACKGROUND_GIF = "spaceinvaders/Images";
    private ImageIcon img = new ImageIcon(PATH_BACKGROUND_GIF);
    private String archivoSeleccionado;
    private GamePanel gamePanel;
    private SpaceInvaders spaceInvaders;

    public Principal() {
        initComponents();
        gamePanel = new GamePanel(this);
        btn_NewGame.setBorderPainted(false);
        btn_NewGame.setFocusPainted(false);

        btn_Continuar.setBorderPainted(false);
        btn_Continuar.setFocusPainted(false);

        btn_PuntajeMaximo.setBorderPainted(false);
        btn_PuntajeMaximo.setFocusPainted(false);

        btn_Salir.setBorderPainted(false);
        btn_Salir.setFocusPainted(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuPrincipal = new javax.swing.JPanel();
        btn_NewGame = new javax.swing.JButton();
        btn_Continuar = new javax.swing.JButton();
        btn_PuntajeMaximo = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        pnlCargarPartida = new javax.swing.JPanel();
        btn_BuscarJuego = new javax.swing.JButton();
        btn_CargarJuego = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlMenuPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        btn_NewGame.setBackground(new java.awt.Color(0, 0, 0));
        btn_NewGame.setForeground(new java.awt.Color(255, 255, 255));
        btn_NewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_NewGame.png"))); // NOI18N
        btn_NewGame.setBorder(null);
        btn_NewGame.setBorderPainted(false);
        btn_NewGame.setContentAreaFilled(false);
        btn_NewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_NewGame.setOpaque(true);
        btn_NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewGameActionPerformed(evt);
            }
        });

        btn_Continuar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Continuar.png"))); // NOI18N
        btn_Continuar.setBorder(null);
        btn_Continuar.setBorderPainted(false);
        btn_Continuar.setContentAreaFilled(false);
        btn_Continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ContinuarActionPerformed(evt);
            }
        });

        btn_PuntajeMaximo.setBackground(new java.awt.Color(0, 0, 0));
        btn_PuntajeMaximo.setForeground(new java.awt.Color(255, 255, 255));
        btn_PuntajeMaximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Puntajes.png"))); // NOI18N
        btn_PuntajeMaximo.setBorder(null);
        btn_PuntajeMaximo.setBorderPainted(false);
        btn_PuntajeMaximo.setContentAreaFilled(false);
        btn_PuntajeMaximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_Salir.setBackground(new java.awt.Color(0, 0, 0));
        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Salir.png"))); // NOI18N
        btn_Salir.setBorder(null);
        btn_Salir.setBorderPainted(false);
        btn_Salir.setContentAreaFilled(false);
        btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/titulo.png"))); // NOI18N

        javax.swing.GroupLayout pnlMenuPrincipalLayout = new javax.swing.GroupLayout(pnlMenuPrincipal);
        pnlMenuPrincipal.setLayout(pnlMenuPrincipalLayout);
        pnlMenuPrincipalLayout.setHorizontalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_Continuar)))
                .addGap(173, 173, 173))
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_PuntajeMaximo))
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btn_Salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuPrincipalLayout.setVerticalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPrincipalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(btn_NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Continuar)
                .addGap(18, 18, 18)
                .addComponent(btn_PuntajeMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Salir)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenuPrincipal, "pnlMenuPrincipal");

        pnlCargarPartida.setBackground(new java.awt.Color(0, 0, 0));
        pnlCargarPartida.setPreferredSize(new java.awt.Dimension(400, 450));

        btn_BuscarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Buscar.png"))); // NOI18N
        btn_BuscarJuego.setBorder(null);
        btn_BuscarJuego.setBorderPainted(false);
        btn_BuscarJuego.setContentAreaFilled(false);
        btn_BuscarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_BuscarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarJuegoActionPerformed(evt);
            }
        });

        btn_CargarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Cargar.png"))); // NOI18N
        btn_CargarJuego.setBorder(null);
        btn_CargarJuego.setBorderPainted(false);
        btn_CargarJuego.setContentAreaFilled(false);
        btn_CargarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_CargarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CargarJuegoActionPerformed(evt);
            }
        });

        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Back.png"))); // NOI18N
        btn_Back.setBorder(null);
        btn_Back.setBorderPainted(false);
        btn_Back.setContentAreaFilled(false);
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCargarPartidaLayout = new javax.swing.GroupLayout(pnlCargarPartida);
        pnlCargarPartida.setLayout(pnlCargarPartidaLayout);
        pnlCargarPartidaLayout.setHorizontalGroup(
            pnlCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCargarPartidaLayout.createSequentialGroup()
                .addGroup(pnlCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_BuscarJuego)
                        .addGroup(pnlCargarPartidaLayout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(btn_CargarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCargarPartidaLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btn_Back)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        pnlCargarPartidaLayout.setVerticalGroup(
            pnlCargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCargarPartidaLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(btn_BuscarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(btn_CargarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );

        getContentPane().add(pnlCargarPartida, "pnlCargarPartida");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewGameActionPerformed
        this.setVisible(false);
        SpaceInvaders spaceInvaders = new SpaceInvaders(this, gamePanel);
    }//GEN-LAST:event_btn_NewGameActionPerformed

    private void btn_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ContinuarActionPerformed
        mostrarPanel("pnlCargarPartida");
    }//GEN-LAST:event_btn_ContinuarActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        mostrarPanel("pnlMenuPrincipal");
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_BuscarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarJuegoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("src/spaceinvaders/Juegos")); // Directorio inicial
        int result = fileChooser.showOpenDialog(this); // Mostrar el diálogo de selección de archivo

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filename = selectedFile.getAbsolutePath();

            // Llamar al método para cargar el estado del juego
            GameStateManager.loadGameState(filename, gamePanel); // Asegúrate de que gamePanel esté inicializado
            this.setVisible(false);
            SpaceInvaders spaceInvaders = new SpaceInvaders(this, gamePanel);
//            spaceInvaders.setVisible(true);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Selección de archivo cancelada.");
        }
    }//GEN-LAST:event_btn_BuscarJuegoActionPerformed

    private void btn_CargarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CargarJuegoActionPerformed


    }//GEN-LAST:event_btn_CargarJuegoActionPerformed
// Método para mostrar un panel específico

    public void mostrarPanel(String panelName) {
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), panelName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_BuscarJuego;
    private javax.swing.JButton btn_CargarJuego;
    private javax.swing.JButton btn_Continuar;
    private javax.swing.JButton btn_NewGame;
    private javax.swing.JButton btn_PuntajeMaximo;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCargarPartida;
    private javax.swing.JPanel pnlMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
